#!/usr/bin/env python3

# TODO
import os
import sys

from analyzer import Analyzer
import helpers
from termcolor import colored

def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweet user_screen_name")
        
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    analyzer = Analyzer(positives,negatives)
    
    tweets = helpers.get_user_timeline(sys.argv[1])
    if tweets == None:
        sys.exit()
    else:
        for tweet in tweets:
            score = analyzer.analyze(tweet)
            if score > 0.0:
                print(colored(tweet,"green"))
            elif score < 0.0:
                print(colored(tweet,"red"))
            else:
                print(colored(tweet,"yellow"))
                
if __name__ == "__main__":
    main()
    
            
